language: node_js
node_js:
  - "stable"
sudo: false

cache:
  directories:
  - $HOME/phantomjs

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
  firefox: latest

before_install:
- firefox --version 2>/dev/null
- google-chrome --product-version
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start


script: 
  - node ./bin/sitespeed.js --sites mygento.txt -n 1  -b firefox -n 1
